/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelperTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Helper classUnderTest = new Helper();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
