apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-ui
  labels:
    name: swagger-ui
spec:
  rules:
  - host: swagger-ui.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: swagger-ui
            port:
              number: 9090
  tls:
  - hosts:
    - swagger-ui.localhost
