/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import java.net.InetAddress;

public class Helper {
    public boolean someLibraryMethod() {
        return true;
    }

    public static String hostname() {
        try {
            return InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            System.err.println(e);
            return "Unknown";
        }
    }

}
