FROM node:16 AS build

# Create app directory
WORKDIR /app

# Bundle app source
COPY . .

# Dependencies
RUN yarn install

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD curl -fk http://localhost:3000/ || exit 1
CMD [ "yarn", "run", "start"]