FROM node:16 AS build

# Create app directory
WORKDIR /app

# Bundle app source
COPY . .

# Dependencies
RUN yarn install
# Build
RUN yarn build


FROM nginx:stable-alpine AS runtime
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD curl -f http://localhost:3000/ || exit 1
CMD ["nginx", "-g", "daemon off;"]